"""Content generation for Mimeo sites."""

from pathlib import Path


def generate_minimal_site(domain: str, output_dir: Path) -> None:
    """Generate a minimal landing page for a domain.

    Creates a simple, elegant landing page displaying the domain name
    in the style of mimeo.lol.

    Args:
        domain: Domain name to display
        output_dir: Directory to write the HTML file to

    Raises:
        OSError: If unable to create directory or write file
    """
    # Ensure output directory exists
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate HTML content with domain name
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{domain}</title>
    <style>
        body {{
            margin: 0;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: #1a1a1a;
            color: #e0e0e0;
            font-family: sans-serif;
            font-size: 2rem;
        }}
        .domain {{
            letter-spacing: 0.5rem;
        }}
    </style>
</head>
<body>
    <div class="domain">{_format_domain(domain)}</div>
</body>
</html>
"""

    # Write index.html
    index_path = output_dir / "index.html"
    index_path.write_text(html_content)

    # Create GitHub Actions workflow
    workflow_dir = output_dir / ".github" / "workflows"
    workflow_dir.mkdir(parents=True, exist_ok=True)

    workflow_content = """# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
"""

    workflow_path = workflow_dir / "static.yml"
    workflow_path.write_text(workflow_content)

    # Create README
    readme_content = f"""# {domain}

A minimal static website hosted on GitHub Pages.

Generated by [Mimeo](https://github.com/pborenstein/mimeo).
"""

    readme_path = output_dir / "README.md"
    readme_path.write_text(readme_content)


def _format_domain(domain: str) -> str:
    """Format domain name with spaces between characters.

    Args:
        domain: Domain name to format

    Returns:
        Domain name with spaces between each character
    """
    return " ".join(domain)
